name: run tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python -m pip install requests
      - run: python -m pip install -e .
      - run: python tests/device_state_tests.py
      - run: python tests/env_tests.py
      - run: python tests/get_config_value_tests.py
      - run: python tests/device_requests_tests.py
